global:
  spring:
    dbUrl: "jdbc:postgresql://postgresql:5432/"
    dbUsername: "postgres"
    dbPassword: "postgres"
    useDefaultConsul: false
    env:
      SPRING_ACTIVEMQ_BROKER_URL: "tcp://activemq:61616"
#     Выключаем tracing, чтобы не сыпал ошибками в логах
      SPRING_SLEUTH_ENABLED: 'false'
      SPRING_ZIPKIN_ENABLED: 'false'
      MANAGEMENT_TRACING_SAMPLING_PROBABILITY: '0.0'

genericServices:
  postgresql:
    enabled: true
    storageClassName: 'nfs-delete'

  activemq:
    enabled: true
