include:
  - project: ${PIPELINE_REPOSITORY_PREFIX}devenv/gitlab/pipelines
    file:
      - merge-request.gitlab-ci.yml
      - jira.gitlab-ci.yml
      - dev-stand.gitlab-ci.yml

build and verify:
  variables:
    MAVEN_GOAL: verify
    JDK_VERSION: 'jdk21'
    MAVEN_IMAGE_VERSION: 'v5'
    NODE_VERSION: 'node22'

# Т.к. у нас нет dev-стенда -- убираем post-dev, чтобы в Jira не проставлялась дата установки на develop
post dev:
  rules:
    - when: never

# Т.к. у нас нет dev-стенда -- убираем deploy dev stand
# Нам из dev-stand.gitlab-ci.yml нужен только build
deploy dev stand:
  rules:
    - when: never
