Инструкция:
1. Если подключался стартер синхронизации то нужно добавить в pom прикладного модуля зависимость(дополнительно к rdm-sync-init-spring-boot-starter)
если в нем планируется при запуске так же добавлять/обновлять маппинги и таблицы справочников в автоматическом режиме.
    ```xml
    <dependency>
        <groupId>ru.i-novus.ms.rdm.sync</groupId>
        <artifactId>rdm-sync-spring-boot-starter</artifactId>
        <version>${rdm.sync.version}</version>
    </dependency>
    ```
2. Больше не используются настройки rdm-sync.change_data.mode, rdm-sync.export.to_rdm.cron, rdm-sync.export.to_rdm.delay и связанная с ними функция экспорта.
Настройки можно удалить

3. Теперь liquibase который добавляет таблицы нужные для синхронизации выполняется до liquibase-а прикладной системы. Раньше было наоборот.
Если это поведение не учитывалось в прикладной системе, то никакие изменения связанные с этим проводить не нужно

4. Добавлена настройка rdm-sync.auto-create.enrich-comments.mode, которая определяет режим запроса в НСИ отсутствующих в маппинге комментариев для таблиц и колонок: NEVER - не запрашивать отсутсвующие комментарии, ON_CREATE - запрашивать отсутствющие комментарии только при создании новых таблиц, ALWAYS - всегда запрашивать отсутствующие комментарии. По умолчанию NEVER.
Чтобы заполнить комментарии для старых таблиц, рекомендуется при одном из запусков установить режим ALWAYS, затем вернуть значение по умолчанию. При добавлении новых справочников рекомендуется указывать в маппинге комментарии к таблицам и колонкам, чтобы не было необходимости периодически включать обновление из НСИ.

== 2.0.0
jdk 21, n2o-boot 7.0.0, spring-boot 3.5.3
