version: "3.6"

services:

  db:
    volumes:
      - rdm-sync-db-data:/pg/11/data
    ports:
      - 5432
    command: postgres -c 'max_connections=500'
    deploy:
      resources:
        limits:
          memory: 1024M
      placement:
        constraints:
        - node.labels.type == db

  rdm-sync-service:
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/rdm_sync

volumes:
  rdm-sync-db-data:
