version: "3.6"

services:
  sync:
    build:
      context: rdm-sync-service/
      args:
        JAR_FILE: target/rdm-sync-service.jar

  sync-db:
    build:
      context: rdm-sync-db/
      args:
        DOCKER_REGISTRY: ${DOCKER_REGISTRY}
